language: python

python:
  - "3.6.6"

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432

before_script:
  - createdb ensemble_test

before_install:
  - cd backend

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install pyYAML


script:
  - python -m pytest  --cov=flaskr

after_success:
  - coveralls