"""empty message

Revision ID: 844d94daab07
Revises: 
Create Date: 2020-01-09 20:36:41.330775

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '844d94daab07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=250), nullable=False),
                    sa.Column('gender', sa.String(length=250), nullable=False),
                    sa.Column('birth_date', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('movies',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=150), nullable=False),
                    sa.Column('release_date', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('movie_crew',
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.Column('actor_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
                    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
                    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_crew')
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
